name: 'CI'
on:
  push:
    tags:
      - '*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get current tag name
        id: current_tag
        run: echo "::set-output name=TAGNAME::$(git describe --abbrev=0 --tags)"
      - name: Get previous tag name
        id: previous_tag
        run: echo "::set-output name=TAGNAME::$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))"
      - name: Get date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Generate
        id: generate
        uses: mikepenz/release-changelog-builder-action@main
        with:
          fromTag: ${{ steps.previous_tag.outputs.TAGNAME }}
          toTag: ${{ steps.current_tag.outputs.TAGNAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{steps.generate.outputs.changelog}} 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create local changes
        run: |
           echo ${{steps.generate.outputs.changelog}} | cat - CHANGELOG.md > temp && mv temp CHANGELOG.md
           git add CHANGELOG.md
      - name: Commit files
        run: |
           git config --local user.email "github-actions[bot]@users.noreply.github.com"
           git config --local user.name "github-actions[bot]"
           git commit -am "changelog: updated after release build"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "master"
